export const posts = [
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 300,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Teste',
        categorySlug: 'hugo',
        title: 'Testando post estatico em blog para carregamento rapido',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'Testando posts para ver se vai carregar rapido',
        author: 'Hugo Teste',
        date: '20/10/1997',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },

]