export const posts = [
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 300,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },
    {
        image: '/images/moldura.webp',
        categoryName: 'Bonitão',
        categorySlug: 'hugo',
        title: 'Hugo bonitão ataca novamente as novinhas assanhadas',
        postSlug: 'conteudo/hugo-bonitao',
        excerpt: 'ataca as novinhas assanhadas em manaus e faz coleções de figurinhas motivadas a sentar',
        author: 'Hugo Bonitão',
        date: '20/10/1997',
        square: 'blogArticleBlockSquare',
        imageWidth: 400,
        imageHeight: 200,
        articleContent: 'coisas a fazer',
    },

]