import Head from "next/head";
import styles from '@styles/blog/blog-page.module.scss'
import articleStyles from '@styles/blog/blog-article.module.scss'
import Layout from "templates/layout";
import { posts } from "mocks";
import { OrganismArticleBlock } from "@organism";
import { SidebarOrganism } from "components/organism/sidebar.organism";

function BlogPage(): JSX.Element {
  return (
    <div>
      <Head>
        <title>Blog | Gualb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.blogMain}>
          <div className={styles.blogContainerPage}>

            <div className={styles.blogFeedPage}>
              <div className={styles.blogContainerBigPost}>
                <h1 className={styles.blogTitlePage}>Artigos recentes</h1>
                <div className={styles.blogArticlesContainer}>
                  {posts.map((post, index) => {
                    if (index < 1) {
                      return (
                        <OrganismArticleBlock
                          index={index}
                          classes={{ block: articleStyles.blogArticleBlockRetangle, img: articleStyles.blogFeatureImageBlockRetangle }}
                          key={index}
                          {...post}
                        ></OrganismArticleBlock>
                      )
                    }
                    return null
                  })}
                </div>
              </div>
              <div className={styles.blogArticlesContainer}>
                {posts.map((post, index) => {
                  if (index >= 1) {

                    return (
                      <OrganismArticleBlock
                        index={index}
                        classes={{ block: articleStyles.blogArticleBlockSquare, img: articleStyles.blogFeatureImageBlockSquare }}
                        key={index}
                        {...post}
                      ></OrganismArticleBlock>
                    )
                  }
                  return null
                })}
              </div>
            </div>
            <div style={{ position: "static" }}>
              <SidebarOrganism></SidebarOrganism>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}

export default BlogPage;
