import Head from 'next/head'

import { HomeBanner, HomeBlogOranism } from '@organism';
import styles from './styles/home/home.module.scss';
import HeaderDesktopOrganism from 'components/organism/header-desktop.organism';
import Layout from 'templates/layout';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <>
          <div className={styles.brandContainer}>


            <div className={styles.firstLayer}>
              <div className={styles.titleBrand}>
                <h1 >Gualb</h1>
              </div>
            </div>





            <div className={styles.lineBackground}>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL1}`}></div>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL2}`}></div>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL3}`}></div>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL4}`}></div>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL5}`}></div>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL6}`}></div>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL7}`}></div>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL8}`}></div>
              <div className={`${styles.lineBackgroundL} ${styles.lineBackgroundL9}`}></div>
            </div>
          </div>
        </>

      </Layout>
      {/* <div style={{ width: '100%', height: 600 }}></div>
      <HomeBlogOranism></HomeBlogOranism> */}
    </div>
  )
}
