import Head from 'next/head'

import {Hello} from '@atoms'
import {HomeBanner, HomeBlogOranism} from '@organism'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <HomeBanner></HomeBanner>
        <div style={{width: '100%', height:600}}></div>
        <HomeBlogOranism></HomeBlogOranism>
    <Hello/>
    </div>
  )
}
